### ISSUE TITLE
os x注入问题

### ISSUE THREAD

**Issue by MarStarck** [tboox/itrace#2]
我在mac上想动态跟踪一些函数，按照第4条找了macSubstrate，但是它的插件只支持.bundle或者.framework，我用ldid -s并没有生成这样的文件。请问该怎么进行下去？

**Comment by waruqi** [comment]
第四部主要是针对mobile设备的。。mac的我好久没测试了，之前也是可以的。。你可以尝试直接用自带的 itracer 注入下试试，不行的话，可以网上再找找其他的注入工具，只要能够吧 itrace.dylib 成功注入到 对方进程，就可以trace了。。

**Comment by MarStarck** [comment]
恩，直接xmake f -p macosx -a x86_64可以编译运行，但是会报segmentation fault 11，不知道是什么数组会在64位系统下指针越界？

**Comment by waruqi** [comment]
是  itrace.dylib crash了？ 还是 itrace注入程序本身 crash？如果只是itrace crash没关系的，他只是个注入器而已，如果是  itrace.dylib crash 了。。可以参考readme第一点说明，通过配置：`<classname args="0" />` 禁用某些class的参数打印：

> 注： 尽量不要去hook， 频繁调用的class， 比如 UIView NSString， 否则会很卡，操作就不方便了。 注： 如果挂接某个class， 中途打印参数信息挂了， 可以在对应的类名后面 加上 args="0" 属性， 来禁止打印参数信息， 这样会稳定点。 如果要让所有类都不打印参数信息， 可以直接设置：

**Comment by MarStarck** [comment]
它应该还没注入成功就crash了，才走到找到pid这一步:

```
sudo ./itracer Instruments
[itracer]: [itrace]: name: Instruments, pid: 573
Segmentation fault: 11
```

**Comment by MarStarck** [comment]
另外我没找到它查明arch的逻辑，就在prefix里强行def了x64并undef了其他的arch，不知道这样做对不对

**Comment by waruqi** [comment]
哦。。那就是注入问题了，，注入这个程序 我好久没更新了，64bits上也许是有些问题，你可以调下，或者可以用第三方的注入工具，吧 itrace.dylib 注入到 你需要hook的进程中去就行了。

**Comment by MarStarck** [comment]
我用第三方工具在测试app中注入成功了
```
[itrace]: [itrace]: init: ..
[itrace]: [itrace]: init: config: itrace.xml: ..
[itrace]: [itrace]: init: config: ok
[itrace]: [itrace]: chook: method_size: 255
[itrace]: [itrace]: mmapmaxn: 24480, mmapbase: 0x101ba2000
[itrace]: [itrace]: init: ok
```
现在一个小小的问题就是对于没有命令行输出的app，怎么看到结果呀？我设置了tb_trace_mode_file但貌似并不会打到文件里。。。

**Comment by MarStarck** [comment]
mac上自带的程序是否有注入保护？我试了几个app，发现finder注入会自动重启，xcode/instruments注入后没反应，chrome倒是可以注入成功并正常运作。

**Comment by waruqi** [comment]
是否有保护，这个我最近也没怎么研究过，要不你百度下看看。。
