### ISSUE TITLE
64位注入相关

### ISSUE THREAD

**Issue by cl0udz** [tboox/itrace#3]
测试了一波，64位注入除了要把itrace.xml和dylib放到对应位置，还需要在app的document文件夹下也放一个itrace.xml？否则一开始init就歇逼了。我是直接复制了一份过去，就可以跑起来了。

不知道这个操作对不对？

**Comment by waruqi** [comment]
只要跑起来ok，操作就没啥问题。

- 如果trace系统进程，itrace.xml放到/tmp/下就行了
- 如果要trace app进程，是要放到docs目录的，因为注入进去后，dylib收到沙盒限制，访问不到/tmp。。

**Comment by zhangkn** [comment]
[itracer]: [itrace]: task_for_pid: 790 failed, errno: 60

**Comment by waruqi** [comment]
@zhangkn itracer 这个注入器 已经在arm64上失效了，可以借用substrate将itrace.dylib注入进去，具体请看README说明。。
